[tool.poetry]
name = "boto3"
version = "0.1.0"
description = "aws sdk for python"
authors = ["nimoes"]

[tool.poetry.dependencies]
python = "^3.8"
loguru = "^0.6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
